[build-system]
requires = ["setuptools", "wheel", "numpy>=1.15", "Cython>=0.29"]


[tool.cibuildwheel.overrides]
build-verbosity = 1
before-all = "uname -a"
select = "cp311*"
linux = {archs = ["x86_64"]}
macos = {archs = ["x86_64", "arm64"]}