[build-system]
requires = ["setuptools", "wheel", "numpy>=1.15", "Cython>=0.29"]


[tool.cibuildwheel]
build-verbosity = 1
before-all = "uname -a"


[tool.cibuildwheel.linux]
archs = "x86_64"
build = "cp311-manylinux*"