name: Build Wheels

on:
  push:
    branches:
      - deploy



jobs:


  build_dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pymoo
        run: |
          python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist

  merge_dist:
    runs-on: ubuntu-latest
    needs: [build_dist]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: pymoo
          delete-merged: true
